---
title: "CourseworkQ1"
author: "Chris_Pang"
date: "2024-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown for Coursework 2023/2024 Q1, Student ID: 220457882


This first part of codes are for Q1b)
```{r Metropolis-Hastings Algorithm}

library(ggplot2)

# Define the probability density function
f <- function(x) {
  1/2 * exp(-abs(x))
}

# Metropolis-Hastings algorithm
metropolis <- function(N, initial_x, s) {
  x <- numeric(N)
  x[1] <- initial_x
  
  for (i in 2:N) {
    x_star <- rnorm(1, mean = x[i - 1], sd = s)
    ratio <- f(x_star) / f(x[i - 1])
    
    if (runif(1) < ratio) {
      x[i] <- x_star
    } else {
      x[i] <- x[i - 1]
    }
  }
  
  x
}

# Parameters
N <- 10000  # Number of iterations
initial_x <- 0  # Initial value
s <- 1  # Standard deviation for the proposal distribution

# Run the Metropolis-Hastings algorithm
samples <- metropolis(N, initial_x, s)

# Plot histogram and kernel density plot with true distribution
x_values <- seq(min(samples), max(samples), length.out = 300)
true_density <- f(x_values)

# Create a data frame for ggplot
data <- data.frame(samples = samples)
true_data <- data.frame(x_values, true_density)

# Plotting
p <- ggplot(data, aes(x = samples)) +
  geom_histogram(aes(y = ..density..), bins = 50, fill = "blue", alpha = 0.4) +
  geom_density(color = "purple") +
  geom_line(data = true_data, aes(x = x_values, y = true_density), color = "red", size = 0.4) +
  labs(title = "Metropolis-Hastings Algorithm with Histogram and Kernel Density",
       x = "Sample Values",
       y = "Density") +
  theme_minimal()
print(p)

# Calculate and report sample mean and standard deviation
sample_mean <- mean(samples)
sample_std <- sd(samples)

cat("Sample Mean:", sample_mean, "\n")
cat("Sample Standard Deviation:", sample_std, "\n")
```


This second part of codes are for Q1b)
```{r }
# Function to run Metropolis-Hastings algorithm for a single chain
metropolis_chain <- function(N, initial_x, s) {
  x <- numeric(N)
  x[1] <- initial_x
  
  for (i in 2:N) {
    randomXStar <- rnorm(1, mean = x[i - 1], sd = s)
    ratio <- f(randomXStar) / f(x[i - 1])
    u <- runif(1)
    
    if (u < ratio) {
      x[i] <- randomXStar
    } else {
      x[i] <- x[i - 1]
    }
  }
  
  return(x)
}

# Function to calculate Rb value
calculate_Rb <- function(chains) {
  J <- length(chains)
  N <- length(chains[[1]])
  
  Mj <- sapply(chains, function(chain) mean(chain))
  Vj <- sapply(chains, function(chain) var((chain - mean(chain))^2))
  
  W <- sum(Vj) / J
  M <- mean(Mj)
  B <- sum((Mj - M)^2) / J
  
  var_hat <- B + W
  Rb <- sqrt(var_hat / W)
  
  return(Rb)
}


set.seed(123)

# Setting Parameters
N <- 2000  # Number of iterations
J <- 4  # Number of chains
s_values <- seq(0.001, 1, length.out = 100)  # Grid of s values

# Run Metropolis-Hastings for different s values and calculate Rb
Rb_values <- numeric(length(s_values))

for (i in seq_along(s_values)) {
  chains <- replicate(J, metropolis_chain(N, initial_x = 0, s = s_values[i]), simplify = FALSE)
  Rb_values[i] <- calculate_Rb(chains)
}

# Plot Rb values over the grid of s values
plot.new()  # Call plot.new() to initiate a new plot
plot(s_values, Rb_values, type='l', col='blue', lwd=2, xlab='s values', ylab='R hat values', main='Rb Values over a Grid of s Values')
abline(h=1.05, col='red', lty='dashed', lw=2)  # Adding a line for reference 
legend('topright', legend=c('Rb Values', 'Threshold (1.05)'), col=c('blue', 'red'), lty=1:1, cex=0.8)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
